### ISSUE TITLE
Prefix 'rafc' working differently

### ISSUE THREAD

**Issue by badalsaibo** [xianghongai/vscode-react-snippet#1]
Earlier, when I typed `rafc`, it would create a react arrow functional component and export it by default. Now it doesn't export, neither imports React.'

E.g For a file named 'Card.js', the prefix `rafc` would do this

```javascript
import React from 'react'

const Card = (props) => {
  return (
    <>
    </>
  )
}

export default Card
```

Instead, now it only does,

```javascript
const Card = (props) => {
  return (
    <>
    </>
  )
};

```

There's no import and export. 

Is it the default behaviour now? I clearly remember doing as described earlier.

**Comment by xianghongai** [comment]
Hi, heyDante, 

Function components will all be instantiated at the end, but arrow functions do not have `this`. It is inappropriate to declare components with arrow functions. I have removed support for arrow functions from the source code. In addition, arrow functions are not recommended in the Airbnb guide. Declare the component ([Class vs React.createClass vs stateless](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless)).

**Comment by badalsaibo** [comment]
A lot of use cases prefer the Arrow Syntax. I have moved to other extension for the time being.

**Comment by xianghongai** [comment]
Airbnb guide:

And if you don’t have state or refs, prefer normal functions (not arrow functions) over classes:

```js
// bad
class Listing extends React.Component {
  render() {
    return <div>{this.props.hello}</div>;
  }
}

// bad (relying on function name inference is discouraged)
const Listing = ({ hello }) => (
  <div>{hello}</div>
);

// good
function Listing({ hello }) {
  return <div>{hello}</div>;
}
```

In addition, from the concepts of "component" and "instance", arrow functions are not recommended. Arrow functions are mainly used to write data processing logic. It has no concept of context.

good luck.
